const cars = [
    {
        id: 1,
        url: "../../img/car.jpg",
        fuel: "Petrol",
        gear: "Automatic",
        price: 2000,
        seats: 6,
    },
    {
        id: 2,
        url: "../../img/car1.jpg",
        fuel: "Diesel",
        gear: "Manual",
        price: 1800,
        seats: 4,
    },
    {
        id: 3,
        url: "../../img/car2.jpg",
        fuel: "Petrol",
        gear: "Automatic",
        price: 1700,
        seats: 4,
    },
    {
        id: 4,
        url: "../../img/car.jpg",
        fuel: "Petrol",
        gear: "Automatic",
        price: 2000,
        seats: 6,
    },
    {
        id: 5,
        url: "../../img/car1.jpg",
        fuel: "Diesel",
        gear: "Manual",
        price: 1800,
        seats: 4,
    },
    {
        id: 6,
        url: "../../img/car2.jpg",
        fuel: "Petrol",
        gear: "Automatic",
        price: 1700,
        seats: 4,
    },
    {
        id: 7,
        url: "../../img/car.jpg",
        fuel: "Petrol",
        gear: "Automatic",
        price: 2000,
        seats: 6,
    },
    {
        id: 8,
        url: "../../img/car1.jpg",
        fuel: "Diesel",
        gear: "Manual",
        price: 1800,
        seats: 4,
    },
    {
        id: 9,
        url: "../../img/car2.jpg",
        fuel: "Petrol",
        gear: "Automatic",
        price: 1700,
        seats: 4,
    },
];

exports.carsArray = cars;
